export  const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!
export const  WORKSPACE_ID =  process.env.NEXT_PUBLIC_APPWRITE_WORKSPACES_ID!
export const  MEMBERS_ID = process.env.NEXT_PUBLIC_APPWRITE_MEMBERS_ID!
export const  PROJECTS_ID = process.env.NEXT_PUBLIC_APPWRITE_PROJECTS_ID!
export const  TASKS_ID = process.env.NEXT_PUBLIC_APPWRITE_TASKS_ID!
export const  TABLE_ID = process.env.NEXT_PUBLIC_APPWRITE_TABLE_ID!
export const  IMAGES_BUCKET_ID =  process.env.NEXT_PUBLIC_APPWRITE_IMAGES_BUCKET_ID!
export const  ANALYZE_ID = process.env.NEXT_PUBLIC_APPWRITE_ANALYZE_ID!
